<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : StemRules.xml
    Created on : March 11, 2011, 7:42 PM
    Author     : Ben Preece
    Description:

    Noun Paradigms: (lemma -> plural)
        Noun Class 1        consonant noun stems
            Noun Class 1A       regular consonant noun stems: jiimaan (X -> Xag)
            Noun Class 1B       shorter consonant noun stems: nika (X -> Xg)
            Noun Class 1C       consonant /ny/ noun stems: awesiinh (Xnh -> Xnyag)
            Noun Class 1D       consonant /y/ noun stems: nimaamaa (X -> Xyag)
        Noun Class 2        long vowel-w noun stems
            Noun Class 2A       w-loss noun stems: anishinaabe (X -> Xg)
            Noun Class 2B       /w/ noun stems: ikwe (X -> wag)
        Noun Class 3        short vowel-w noun stems: inini (X -> Xwag)
        Noun Class 4        consonant-w noun stems
            Noun Class 4A       /oo/ noun stems: mitig (X -> Xoog)
            Noun Class 4B       /w/ noun stems: amik (X -> Xoog)
            Noun Class 4C       shorter consonant-w noun stems: makwa (X -> Xg)
        Noun Class 5        consonant-y noun stems
            Noun Class 5A       regular consonant-y noun stems: asin (X -> Xiig)
            Noun Class 5B       shorter consonant-y noun stems: aki (Xi -> Xiig)
        Noun Class 6        special /aa/ noun stems: inzid (X -> Xag)

    Verb Paradigms: (lemma -> 3s neg.)
        VII                 intrasitive inanimate verbs
            VII Class 1         vii long vowel stems
            VII Class 2         vii short vowel stems
            VII Class 2A    vii short vowel stems; no /n/
            VII Class 2B    vii short vowel stems; some /n/
            VII Class 2C    vii short vowel stems; always /n/
            VII Class 3         vii consonant stems
            VII Class 3A    vii consonant /d/ stems
            VII Class 3B    vii consonant /n/ stems
        VAI                 intransitive animate verbs
            VAI Class 1         vai vowel stem
            VAI Class 1A    vai long vowel stems
            VAI Class 1B    vai short vowel stems
            VAI Class 2         vai consonant stems
            VAI Class 2A    vai consonant /n/ stems
            VAI Class 2B    vai consonant /m/ stems
        VAI2                vai2 /am/ stems
        VTI                 transitive inanimate verbs
            VTI1                vti /am/ stems
            VTI2                vti /oo/ stems
            VTI3                vti /i/ stems
            VTI4                vti /aa/ stems
        VTA                 transitive animate verbs
            VTA Class 1     vta consonant stems
            VTA Class 1A    vta regular consonant stems
            VTA Class 1B    vta shorter consonant stems
            VTA Class 2     vta changeable /N/ stems
            VTA Class 2A    vta regular changeable /N/ stems
            VTA Class 2B    vta shorter changeable /N/ stems
            VTA Class 3     vta changeable /s/ stems
            VTA Class 3A    vta regular changeable /s/ stems
            VTA Class 3B    vta shorter changeable /s/ stems
            VTA Class 4     vta changeable /Nn/ stems
            VTA Class 4A    vta regular changeable /Nn/ stems
            VTA Class 4B    vta shorter changeable /Nn/ stems
            VTA Class 5     vta /aw/ stems
            VTA Class 6     vta consonant-w stems
            VTA Class 6A    vta regular consonant-w stems
            VTA Class 6B    vta shorter consonant-w stems
            VTA Class 7     vta glottal-w stems
            VTA Class 8     vta irregular stems

    The following doc-type describes the required format of this file.
    Basically:

        1)  The root tag is "stem-rules", which comprises zero or more
            "rule-set" tags, which comprise zero or more "rule" tags.

        2)  The stem-rules tag may optionally have a "name" attribute which
            can be used to identify the set of stem rules.

        3)  A "rule-set" is required to have a "name" attribute, which is
            a unique identifier that the stemmer code uses to locate the
            rule-set in the file.

        4)  Each "rule" has two attributes: a "regex" and a "format".

    (See the javadocs for the StemRule class for more information.)
-->
<!DOCTYPE stem-rules [
    <!ELEMENT stem-rules (rule-set*)>
    <!ELEMENT rule-set (rule*)>
    <!ELEMENT rule (EMPTY)>
    <!ATTLIST stem-rules name ID #IMPLIED>
    <!ATTLIST rule-set name ID #REQUIRED>
    <!ATTLIST rule regex CDATA #REQUIRED>
    <!ATTLIST rule format CDATA #REQUIRED>
]>

<stem-rules name="Ojibwe-stemming-rules">
    <!--
        Person prefix rule:  these are used for both nouns and verbs.
    -->
    <rule-set name="1stPersonPrefixRules">
        <!-- 1st person possessor prefixes -->
        <rule regex="nind?([aei].*)" format="{1}" />
        <rule regex="ind?([aei].*)" format="{1}" />
        <rule regex="nd?([aei].*)" format="{1}" />
        <rule regex="nindo(o.*)" format="{1}" />
        <rule regex="indo(o.*)" format="{1}" />
        <rule regex="ndo(o.*)" format="{1}" />
        <rule regex="n(ii.*)" format="{1}" />
        <rule regex="n(oo.*)" format="{1}" />
        <rule regex="nim(b.*)" format="{1}" />
        <rule regex="im(b.*)" format="{1}" />
        <rule regex="m(b.*)" format="{1}" />
        <rule regex="nin([dgjz'].*)" format="{1}" />
        <rule regex="in([dgjz'].*)" format="{1}" />
        <rule regex="n([dgjz'].*)" format="{1}" />
        <rule regex="ni([chkmnpstwy].*)" format="{1}" />
    </rule-set>
    <rule-set name="2ndPersonPrefixRules">
        <!-- 2nd person possessor prefixes -->
        <rule regex="gid([aei].*)" format="{1}" />
        <rule regex="gido(o.*)" format="{1}" />
        <rule regex="g(ii.*)" format="{1}" />
        <rule regex="g(oo.*)" format="{1}" />
        <rule regex="gi([bcdghjkmnpstwyz'].*)" format="{1}" />
    </rule-set>
    <rule-set name="3rdPersonPrefixRules">
        <!-- 3rd person possessor prefixes -->
        <rule regex="od([aei].*)" format="{1}" />
        <rule regex="odo(o.*)" format="{1}" />
        <rule regex="w(ii.*)" format="{1}" />
        <rule regex="od(oo.*)" format="{1}" />
        <rule regex="o([bcdghjkmnpstwyz'].*)" format="{1}" />
    </rule-set>

    <!--
        NOUN RULES:
        +====+====+=====+=====+=====+========+=====+=====+
        |    |    |Dimin|     |     |Poss Pl/|     |Plur/|
        |Poss|Stem|/Cont|Theme|Pejor|Obv Poss|Pret |Obv. |
        +====+====+=====+=====+=====+========+=====+=====+
        | n- | -  |-Vns | -aa |-Vsh |-Vnaan  |-Vban|-Vg  |
        | g- |    |-Vnh | -Vm |     |-Vwaa   |     |-Vn  |
        | w- |    |     |     |     |-Vni    |     |-Vn  |
        |    |    |     |     |     |        |     +=====+
        |    |    |     |     |     |        |     |Loc  |
        |    |    |     |     |     |        |     +=====+
        |    |    |     |     |     |        |     |-Vng |
        |    |    |     |     |     |        +===========+
        |    |    |     |     |     |        |Voc Pl     |
        |    |    |     |     |     |        +===========+
        |    |    |     |     |     |        |-Vdig      |
        |    |    |     |     |     |        |-Vdog      |
        +====+====+=====+=====+=====+========+=====+=====+

        except that for possessed nound, the pejorative ending
        can come before the theme.
    -->
    <rule-set name="singularRules">
        <!-- I,VI -->
        <rule regex="(.*nh)" format="{1}y" />
        <!-- II-IV -->
        <rule regex="(.*[^wy])" format="{1}w" />
        <!-- V -->
        <rule regex="(.*[^wy])" format="{1}y" />
    </rule-set>
    <rule-set name="diminutiveRules">
        <!-- I -->
        <rule regex="(.*ii)ns" format="{1}" />
        <rule regex="(.*)ens" format="{1}" />
        <rule regex="(.*aa)ns" format="{1}nhy" />
        <rule regex="(.*e)ns" format="{1}nhy" />
        <rule regex="(.*ii)ns" format="{1}nhy" />
        <rule regex="(.*oo)ns" format="{1}nhy" />
        <!-- II -->
        <rule regex="(.*aa)ns" format="{1}w" />
        <rule regex="(.*e)ns" format="{1}w" />
        <rule regex="(.*ii)ns" format="{1}w" />
        <rule regex="(.*oo)ns" format="{1}w" />
        <!-- III -->
        <rule regex="(.*)aans" format="{1}aw" />
        <rule regex="(.*)iins" format="{1}iw" />
        <rule regex="(.*)oons" format="{1}ow" />
        <!-- IV -->
        <rule regex="(.*)oons" format="{1}w" />
        <!-- V -->
        <rule regex="(.*)iins" format="{1}y" />
        <!-- VI -->
        <rule regex="(.*)aans" format="{1}" />
        <rule regex="(.*)aans" format="{1}an" />
    </rule-set>
    <rule-set name="contemptiveRules">
        <!-- I -->
        <rule regex="(.*)enhy?" format="{1}" />
        <rule regex="(.*)nhy?" format="{1}nhy" />
        <!-- II, IV -->
        <rule regex="(.*)nhy?" format="{1}w" />
        <!-- III -->
        <rule regex="(.*)aanhy?" format="{1}aw" />
        <rule regex="(.*)iinhy?" format="{1}iw" />
        <rule regex="(.*)oonhy?" format="{1}ow" />
        <!-- V -->
        <rule regex="(.*)iinhy?" format="{1}y" />
        <!-- VI -->
        <rule regex="(.*)aanhy?" format="{1}" />
        <rule regex="(.*)aanhy?" format="{1}an" />
    </rule-set>
    <rule-set name="possesssorThemeRules">
        <!-- I, II, III, IV, V -->
        <rule regex="(.*[aeio]m)" format="{1}" />
        <rule regex="(.*[^imn]im)" format="{1}" />
        <!-- VI -->
        <rule regex="(.*)aam" format="{1}" />
        <rule regex="(.*a)am" format="{1}" />
    </rule-set>
    <rule-set name="pejorativeRules">
        <!-- I -->
        <rule regex="(.*)ish" format="{1}" />
        <rule regex="(.*aa)sh" format="{1}nhy" />
        <rule regex="(.*e)sh" format="{1}nhy" />
        <rule regex="(.*ii)sh" format="{1}nhy" />
        <rule regex="(.*oo)sh" format="{1}nhy" />
        <!-- II -->
        <rule regex="(.*aa)sh" format="{1}w" />
        <rule regex="(.*e)sh" format="{1}w" />
        <rule regex="(.*ii)sh" format="{1}w" />
        <rule regex="(.*oo)sh" format="{1}w" />
        <!-- III -->
        <rule regex="(.*[aio]w)ish" format="{1}" />
        <!-- IV -->
        <rule regex="(.*[^o])osh" format="{1}w" />
        <!-- V -->
        <rule regex="(.*)iish" format="{1}y" />
        <!-- VI -->
        <rule regex="(.*)aash" format="{1}" />
        <rule regex="(.*)aash" format="{1}an" />
    </rule-set>
    <rule-set name="possesssorPluralRules">
        <rule regex="(.*[mn])inaan" format="{1}" />
        <rule regex="(.*[mn])iwaa" format="{1}" />
        <rule regex="(.*[mn])anini" format="{1}" />
    </rule-set>
    <rule-set name="preteriteRules">
        <!-- I,III -->
        <rule regex="(.*)iban" format="{1}" />
        <!-- II -->
        <rule regex="(.*aa)ban" format="{1}w" />
        <rule regex="(.*e)ban" format="{1}w" />
        <rule regex="(.*ii)ban" format="{1}w" />
        <rule regex="(.*oo)ban" format="{1}w" />
        <!-- IV -->
        <rule regex="(.*)oban" format="{1}w" />
        <!-- V -->
        <rule regex="(.*)iiban" format="{1}y" />
        <!-- VI -->
        <rule regex="(.*)aaban" format="{1}" />
        <rule regex="(.*)aaban" format="{1}an" />
        <!-- after possessive plural suffix -->
        <rule regex="(.*naan)iban" format="{1}" />
        <rule regex="(.*waa)ban" format="{1}" />
        <rule regex="(.*ni)ban" format="{1}" />
    </rule-set>
    <rule-set name="pluralAndObviativeRules">
        <!-- animate plural -->
        <!-- I,III,IVb,VI -->
        <rule regex="(.*[^a])ag" format="{1}" />
        <rule regex="(.*aa)nyag" format="{1}nhy" />
        <rule regex="(.*e)nyag" format="{1}nhy" />
        <rule regex="(.*ii)nyag" format="{1}nhy" />
        <rule regex="(.*oo)nyag" format="{1}nhy" />
        <!-- II -->
        <rule regex="(.*aa)g" format="{1}w" />
        <rule regex="(.*e)g" format="{1}w" />
        <rule regex="(.*ii)g" format="{1}w" />
        <rule regex="(.*oo)g" format="{1}w" />
        <!-- IVa -->
        <rule regex="(.*)oog" format="{1}w" />
        <!-- V -->
        <rule regex="(.*)iig" format="{1}y" />
        <!-- inanimate plural / obviative -->
        <!-- I,III,IVb,VI -->
        <rule regex="(.*ii)n" format="{1}" />
        <rule regex="(.*[^a])an" format="{1}" />
        <rule regex="(.*[^i])in" format="{1}" />
        <rule regex="(.*aa)nyan" format="{1}nhy" />
        <rule regex="(.*e)nyan" format="{1}nhy" />
        <rule regex="(.*ii)nyan" format="{1}nhy" />
        <rule regex="(.*oo)nyan" format="{1}nhy" />
        <!-- II -->
        <rule regex="(.*a)n" format="{1}w" />
        <rule regex="(.*e)n" format="{1}w" />
        <rule regex="(.*ii)n" format="{1}w" />
        <rule regex="(.*oo)n" format="{1}w" />
        <!-- IVa -->
        <rule regex="(.*)oon" format="{1}w" />
        <!-- V -->
        <rule regex="(.*)iin" format="{1}y" />
        <!-- plural / obviative after possessor plural suffix -->
        <rule regex="(.*naan)i[ng]" format="{1}" />
        <rule regex="(.*waa)[ng]" format="{1}" />
        <rule regex="(.*ni)[ng]" format="{1}" />
        <!-- Participles -->
        <rule regex="(.*)jig" format="{1}d" />
    </rule-set>
    <rule-set name="locativeRules">
        <!-- NX NLOCA -->
        <!-- I -->
        <rule regex="(.*[^i])ing" format="{1}" />
        <rule regex="(.*aa)nying" format="{1}nhy" />
        <rule regex="(.*e)nying" format="{1}nhy" />
        <rule regex="(.*ii)nying" format="{1}nhy" />
        <rule regex="(.*oo)nying" format="{1}nhy" />
        <!-- II -->
        <rule regex="(.*aa)ng" format="{1}w" />
        <rule regex="(.*e)ng" format="{1}w" />
        <rule regex="(.*ii)ng" format="{1}w" />
        <rule regex="(.*oo)ng" format="{1}w" />
        <!-- III -->
        <rule regex="(.*)iing" format="{1}iw" />
        <rule regex="(.*)aang" format="{1}aw" />
        <!-- IV -->
        <rule regex="(.*[^o])ong" format="{1}w" />
        <!-- V -->
        <rule regex="(.*)iing" format="{1}y" />
        <rule regex="(.*a)ang" format="{1}y" />
        <!-- VI -->
        <rule regex="(.*)aang" format="{1}" />
        <rule regex="(.*)aang" format="{1}an" />
        <!-- after possessive plural -->
        <rule regex="(.*naan)ing" format="{1}" />
        <rule regex="(.*waa)ng" format="{1}" />
        <rule regex="(.*ni)ng" format="{1}" />
    </rule-set>
    <rule-set name="vocativeRules">
        <!-- I -->
        <rule regex="(.*)id[io]g" format="{1}" />
        <rule regex="(.*aa)d[io]g" format="{1}nhy" />
        <rule regex="(.*e)d[io]g" format="{1}nhy" />
        <rule regex="(.*ii)d[io]g" format="{1}nhy" />
        <rule regex="(.*oo)d[io]g" format="{1}nhy" />
        <!-- II -->
        <rule regex="(.*aa)d[io]g" format="{1}w" />
        <rule regex="(.*e)d[io]g" format="{1}w" />
        <rule regex="(.*ii)d[io]g" format="{1}w" />
        <rule regex="(.*oo)d[io]g" format="{1}w" />
        <!-- III -->
        <rule regex="(.*w)id[io]g" format="{1}w" />
        <!-- IV -->
        <rule regex="(.*[^o])od[io]g" format="{1}w" />
        <!-- V -->
        <rule regex="(.*)iid[io]g" format="{1}y" />
        <!-- VI -->
        <rule regex="(.*)aad[io]g" format="{1}" />
        <!-- after possessive plural suffix -->
        <rule regex="(.*waa)d[io]g" format="{1}w" />
        <rule regex="(.*ni)d[io]g" format="{1}w" />
    </rule-set>

    <!--
        VERB RULES
    -->
    <rule-set name="preverbRules">
        <rule regex="aano(.*)" format="{1}" />
        <rule regex="bwaa(.*)" format="{1}" />
        <rule regex="de(.*)" format="{1}" />
        <rule regex="daa(.*)" format="{1}" />
        <rule regex="ga(.*)" format="{1}" />
        <rule regex="gaa(.*)" format="{1}" />
        <rule regex="gad([aeio].*)" format="{1}" />
        <rule regex="ge(.*)" format="{1}" />
        <rule regex="gii(.*)" format="{1}" />
        <rule regex="ji(.*)" format="{1}" />
        <rule regex="jibwaa(.*)" format="{1}" />
        <rule regex="waa(.*)" format="{1}" />
        <rule regex="wii(.*)" format="{1}" />
    </rule-set>
    <rule-set name="conjunctLengthRules">
        <rule regex="e(.*)" format="a{1}" />
        <rule regex="ayaa(.*)" format="aa{1}" />
        <rule regex="aye(.*)" format="e{1}" />
        <rule regex="e(.*)" format="i{1}" />
        <rule regex="aa(.*)" format="ii{1}" />
        <rule regex="we(.*)" format="o{1}" />
        <rule regex="waa(.*)" format="oo{1}" />
        <rule regex="([bdgjmnwz]|zh)e(.*)" format="{1}a{2}" />
        <rule regex="([bdgjmnwz]|zh)ayaa(.*)" format="{1}aa{2}" />
        <rule regex="([bdgjmnwz]|zh)aye(.*)" format="{1}e{2}" />
        <rule regex="([bdgjmnwz]|zh)e(.*)" format="{1}i{2}" />
        <rule regex="([bdgjmnwz]|zh)aa(.*)" format="{1}ii{2}" />
        <rule regex="([bdgjmnwz]|zh)we(.*)" format="{1}o{2}" />
        <rule regex="([bdgjmnwz]|zh)waa(.*)" format="{1}oo{2}" />
        <rule regex="en(da[ansz].*)" format="{1}" />
    </rule-set>
    <!--
        vaiIndependentRules
        vowel stem: minikwe
        consonant stem: dagoshin
        'o' stem: inoomigo
        'i' stem: anwebi
        'am' stem: nisidot
    -->
    <rule-set name="vaiIndependentRules">
        <!-- positive -->
        <!-- 2s, 1s -->
        <rule regex="(.*)" format="{1}" />
        <rule regex="(.*[^aeio])" format="{1}i" />
        <rule regex="(.*[^aeio])" format="{1}o" />
        <rule regex="(.*)am" format="{1}" />
        <!-- 2p -->
        <rule regex="(.*[aeio])m" format="{1}" />
        <rule regex="(.*)im" format="{1}" />
        <rule regex="(.*)aam" format="{1}" />
        <!-- 12, 1p -->
        <rule regex="(.*)min" format="{1}" />
        <rule regex="(.*)imin" format="{1}" />
        <rule regex="(.*)amin" format="{1}" />
        <!-- 3s -->
        <rule regex="(.*)" format="{1}" />
        <rule regex="(.*)am" format="{1}" />
        <!-- 3p -->
        <rule regex="(.*)wag" format="{1}" />
        <rule regex="(.*)og" format="{1}" />
        <rule regex="(.*)amog" format="{1}" />
        <!-- negative -->
        <!-- 2s, 1s, 3s -->
        <rule regex="(.*)siin?" format="{1}" />
        <rule regex="(.*n)ziin?" format="{1}" />
        <rule regex="(.*a)nziin?" format="{1}m" />
        <rule regex="(.*)anziin?" format="{1}" />
        <!-- 2p -->
        <rule regex="(.*)siim" format="{1}" />
        <rule regex="(.*n)ziim" format="{1}" />
        <rule regex="(.*a)nziim" format="{1}m" />
        <rule regex="(.*)anziim" format="{1}" />
        <!-- 12, 1p -->
        <rule regex="(.*)siimin" format="{1}" />
        <rule regex="(.*n)ziiimin" format="{1}" />
        <rule regex="(.*a)nziiimin" format="{1}m" />
        <rule regex="(.*)anziimin" format="{1}" />
        <!-- 3p -->
        <rule regex="(.*)siiwag" format="{1}" />
        <rule regex="(.*)wagsiiwag" format="{1}" />
        <rule regex="(.*n)ziiwag" format="{1}" />
        <rule regex="(.*a)nziiwag" format="{1}m" />
        <rule regex="(.*)anziiwag" format="{1}" />
    </rule-set>
    <rule-set name="vaiPreteriteRules">
        <!-- positive -->
        <!-- 2s, 1s -->
        <rule regex="(.*)naaban" format="{1}" />
        <rule regex="(.*)anaaban" format="{1}" />
        <!-- 2p -->
        <rule regex="(.*)mwaaban" format="{1}" />
        <rule regex="(.*)amwaaban" format="{1}" />
        <!-- 12, 1p -->
        <rule regex="(.*)minaaban" format="{1}" />
        <rule regex="(.*)aminaaban" format="{1}" />
        <!-- 3s -->
        <rule regex="(.*)ban" format="{1}" />
        <rule regex="(.*)aban" format="{1}" />
        <rule regex="(.*)amaban" format="{1}" />
        <!-- 3p -->
        <rule regex="(.*)baniig" format="{1}" />
        <rule regex="(.*)abaniig" format="{1}" />
        <rule regex="(.*)amabaniig" format="{1}" />
        <!-- negative -->
        <!-- 2s, 1s -->
        <rule regex="(.*)siinaaban" format="{1}" />
        <rule regex="(.*n)ziinaaban" format="{1}" />
        <rule regex="(.*a)nziinaaban" format="{1}m" />
        <rule regex="(.*)anziinaaban" format="{1}" />
        <!-- 2p -->
        <rule regex="(.*)siimwaaban" format="{1}" />
        <rule regex="(.*n)ziimwaaban" format="{1}" />
        <rule regex="(.*a)nziimwaaban" format="{1}m" />
        <rule regex="(.*)anziimwaaban" format="{1}" />
        <!-- 12, 1p -->
        <rule regex="(.*)siiminaaban" format="{1}" />
        <rule regex="(.*n)ziiminaaban" format="{1}" />
        <rule regex="(.*a)nziiminaaban" format="{1}m" />
        <rule regex="(.*)anziiminaaban" format="{1}" />
        <!-- 3s -->
        <rule regex="(.*)siiban" format="{1}" />
        <rule regex="(.*n)ziiban" format="{1}" />
        <rule regex="(.*a)nziiban" format="{1}m" />
        <rule regex="(.*)anziiban" format="{1}" />
        <!-- 3p -->
        <rule regex="(.*)siibaniig" format="{1}" />
        <rule regex="(.*n)ziibaniig" format="{1}" />
        <rule regex="(.*a)nziibaniig" format="{1}m" />
        <rule regex="(.*)anziibaniig" format="{1}" />
    </rule-set>
    <rule-set name="vaiDubitativeRules">
        <!-- positive -->
        <!-- 2s, 1s -->
        <rule regex="(.*)naadog" format="{1}" />
        <rule regex="(.*)anaadog" format="{1}" />
        <!-- 2p, 12, 1p. X, 3p, 3' -->
        <rule regex="(.*)" format="{1}" />
        <!-- 3s -->
        <rule regex="(.*[aeio])dog" format="{1}" />
        <!-- negative -->
        <!-- 2s, 1s -->
        <rule regex="(.*)siinaadog" format="{1}" />
        <rule regex="(.*n)ziinaadog" format="{1}" />
        <rule regex="(.*a)nziinaadog" format="{1}m" />
        <rule regex="(.*)siinaadog" format="{1}" />
        <!-- 2p, 12, 1p. X, 3p, 3' -->
        <rule regex="(.*)sii" format="{1}" />
        <!-- 3s -->
        <rule regex="(.*[aeio])siidog" format="{1}" />
    </rule-set>
    <rule-set name="vaiDubitativePreteriteRules">
        <!-- final vowel -->
        <rule regex="(.*)goban" format="{1}" />
        <rule regex="(.*)nigoban" format="{1}" />
        <rule regex="(.*)migoban" format="{1}" />
        <rule regex="(.*)waagoban" format="{1}" />
        <!-- final vowel negative -->
        <rule regex="(.*)siigoban" format="{1}" />
        <rule regex="(.*sii)nigoban" format="{1}" />
        <rule regex="(.*)siimigoban" format="{1}" />
        <rule regex="(.*)siiwaagoban" format="{1}" />
        <!-- final nasal -->
        <rule regex="(.*[mn])agoban" format="{1}" />
        <rule regex="(.*[mn])inigoban" format="{1}" />
        <rule regex="(.*[mn])amigoban" format="{1}" />
        <rule regex="(.*[mn])awaagoban" format="{1}" />
        <!-- final nasal negative -->
        <rule regex="(.*n)ziigoban" format="{1}" />
        <rule regex="(.*n)ziinigoban" format="{1}" />
        <rule regex="(.*n)ziimigoban" format="{1}" />
        <rule regex="(.*n)ziiwaagoban" format="{1}" />
        <rule regex="(.*)nziigoban" format="{1}m" />
        <rule regex="(.*)nziinigoban" format="{1}m" />
        <rule regex="(.*)nziimigoban" format="{1}m" />
        <rule regex="(.*)nziiwaagoban" format="{1}m" />
    </rule-set>
    <rule-set name="vaiConjunctRules">
        <!-- positive -->
        <!-- 2s -->
        <rule regex="(.*)yan" format="{1}" />
        <rule regex="(.*)an" format="{1}" />
        <rule regex="(.*)aman" format="{1}" />
        <!-- 2p -->
        <rule regex="(.*)yeg" format="{1}" />
        <rule regex="(.*)eg" format="{1}" />
        <rule regex="(.*)ameg" format="{1}" />
        <!-- 12 -->
        <rule regex="(.*)yang" format="{1}" />
        <rule regex="(.*)ang" format="{1}" />
        <rule regex="(.*)amang" format="{1}" />
        <!-- 1s -->
        <rule regex="(.*)yaan" format="{1}" />
        <rule regex="(.*)aan" format="{1}" />
        <rule regex="(.*)amaan" format="{1}" />
        <!-- 1p -->
        <rule regex="(.*)yaang" format="{1}" />
        <rule regex="(.*)aang" format="{1}" />
        <rule regex="(.*)amaang" format="{1}" />
        <!-- 3s -->
        <rule regex="(.*)d" format="{1}" />
        <rule regex="(.*n)g" format="{1}" />
        <rule regex="(.*a)ng" format="{1}m" />
        <rule regex="(.*)ang" format="{1}" />
        <!-- 3p -->
        <rule regex="(.*)waad" format="{1}" />
        <rule regex="(.*)owaad" format="{1}" />
        <rule regex="(.*)amowaad" format="{1}" />
        <!-- 3' -->
        <rule regex="(.*)nid" format="{1}" />
        <rule regex="(.*[mn])nid" format="{1}" />
        <rule regex="(.*)aminid" format="{1}" />
        <!-- positive -->
        <!-- 2s -->
        <rule regex="(.*)siiyan" format="{1}" />
        <rule regex="(.*n)ziiyan" format="{1}" />
        <rule regex="(.*a)nziiyan" format="{1}m" />
        <rule regex="(.*)anziiyan" format="{1}" />
        <!-- 2p -->
        <rule regex="(.*)siiyeg" format="{1}" />
        <rule regex="(.*n)ziiyeg" format="{1}" />
        <rule regex="(.*a)nziiyeg" format="{1}m" />
        <rule regex="(.*)anziiyeg" format="{1}" />
        <!-- 12 -->
        <rule regex="(.*)siiyang" format="{1}" />
        <rule regex="(.*n)ziiyang" format="{1}" />
        <rule regex="(.*a)nziiyang" format="{1}m" />
        <rule regex="(.*)anziiyang" format="{1}" />
        <!-- 1s -->
        <rule regex="(.*)siiyaan" format="{1}" />
        <rule regex="(.*n)ziiyaan" format="{1}" />
        <rule regex="(.*a)nziiyaan" format="{1}m" />
        <rule regex="(.*)anziiyaan" format="{1}" />
        <!-- 1p -->
        <rule regex="(.*)siiyaang" format="{1}" />
        <rule regex="(.*n)ziiyaang" format="{1}" />
        <rule regex="(.*a)nziiyaang" format="{1}m" />
        <rule regex="(.*)anziiyaang" format="{1}" />
        <!-- 3s -->
        <rule regex="(.*)siid" format="{1}" />
        <rule regex="(.*n)ziid" format="{1}" />
        <rule regex="(.*a)nziid" format="{1}m" />
        <rule regex="(.*)anziid" format="{1}" />
        <!-- 3p -->
        <rule regex="(.*)siigwaa" format="{1}" />
        <rule regex="(.*n)ziigwaa" format="{1}" />
        <rule regex="(.*a)nziigwaa" format="{1}m" />
        <rule regex="(.*)anziigwaa" format="{1}" />
        <!-- 3' -->
        <rule regex="(.*)siinid" format="{1}" />
        <rule regex="(.*n)ziinid" format="{1}" />
        <rule regex="(.*a)nziinid" format="{1}m" />
        <rule regex="(.*)anziinid" format="{1}" />
    </rule-set>
    <rule-set name="vaiConjunctPreteriteRules">
        <!-- final vowel -->
        <rule regex="(.*)yaambaanh" format="{1}" />
        <rule regex="(.*)yamban" format="{1}" />
        <rule regex="(.*)pan" format="{1}" />
        <rule regex="(.*)nipan" format="{1}" />
        <rule regex="(.*)ngiban" format="{1}" />
        <rule regex="(.*)yaangiban" format="{1}" />
        <rule regex="(.*)yangiban" format="{1}" />
        <rule regex="(.*)yegoban" format="{1}" />
        <rule regex="(.*)waapan" format="{1}" />
        <!-- final vowel negative -->
        <rule regex="(.*)sii?waambaanh" format="{1}" />
        <rule regex="(.*)sii?wamban" format="{1}" />
        <rule regex="(.*)siipan" format="{1}" />
        <rule regex="(.*)siinipan" format="{1}" />
        <rule regex="(.*)siingiban" format="{1}" />
        <rule regex="(.*)sii?waangiban" format="{1}" />
        <rule regex="(.*)sii?wangiban" format="{1}" />
        <rule regex="(.*)sii?wegoban" format="{1}" />
        <rule regex="(.*)sii?waapan" format="{1}" />
        <!-- final nasal -->
        <rule regex="(.*[mn])aambaanh" format="{1}" />
        <rule regex="(.*[mn])amban" format="{1}" />
        <rule regex="(.*n)gipan" format="{1}" />
        <rule regex="(.*)ngipan" format="{1}m" />
        <rule regex="(.*[mn])inipan" format="{1}" />
        <rule regex="(.*[mn])ingiban" format="{1}" />
        <rule regex="(.*[mn])aangiban" format="{1}" />
        <rule regex="(.*[mn])angiban" format="{1}" />
        <rule regex="(.*[mn])egoban" format="{1}" />
        <rule regex="(.*[mn])awaapan" format="{1}" />
        <!-- final nasal negative -->
        <rule regex="(.*n)zii?waambaanh" format="{1}" />
        <rule regex="(.*n)zii?wamban" format="{1}" />
        <rule regex="(.*n)ziipan" format="{1}" />
        <rule regex="(.*n)ziinipan" format="{1}" />
        <rule regex="(.*n)ziingiban" format="{1}" />
        <rule regex="(.*n)zii?waangiban" format="{1}" />
        <rule regex="(.*n)zii?wangiban" format="{1}" />
        <rule regex="(.*n)zii?wegoban" format="{1}" />
        <rule regex="(.*n)zii?waapan" format="{1}" />
        <rule regex="(.*)nzii?waambaanh" format="{1}m" />
        <rule regex="(.*)nzii?wamban" format="{1}m" />
        <rule regex="(.*)nziipan" format="{1}m" />
        <rule regex="(.*)nziinipan" format="{1}m" />
        <rule regex="(.*)nziingiban" format="{1}m" />
        <rule regex="(.*)nzii?waangiban" format="{1}m" />
        <rule regex="(.*)nzii?wangiban" format="{1}m" />
        <rule regex="(.*)nzii?wegoban" format="{1}m" />
        <rule regex="(.*)nzii?waapan" format="{1}m" />
    </rule-set>
    <rule-set name="vaiConjunctDubitativeRules">
        <!-- final vowel -->
        <rule regex="(.*)waanen" format="{1}" />
        <rule regex="(.*)wanen" format="{1}" />
        <rule regex="(.*)gwenh" format="{1}" />
        <rule regex="(.*)nigwenh" format="{1}" />
        <rule regex="(.*)ngwenh" format="{1}" />
        <rule regex="(.*)waangen" format="{1}" />
        <rule regex="(.*)wangwen" format="{1}" />
        <rule regex="(.*)wegwen" format="{1}" />
        <rule regex="(.*)waagwenh" format="{1}" />
        <!-- final vowel negative -->
        <rule regex="(.*)sii?waanen" format="{1}" />
        <rule regex="(.*)sii?wanen" format="{1}" />
        <rule regex="(.*)gsii?wenh" format="{1}" />
        <rule regex="(.*)sii?nigwenh" format="{1}" />
        <rule regex="(.*)sii?ngwenh" format="{1}" />
        <rule regex="(.*)sii?waangen" format="{1}" />
        <rule regex="(.*)sii?wangwen" format="{1}" />
        <rule regex="(.*)sii?wegwen" format="{1}" />
        <rule regex="(.*)sii?waagwenh" format="{1}" />